FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o middleware services/middleware/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/middleware .
EXPOSE 8080
CMD ["./middleware"]
