FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o mock-erp cmd/mock-erp/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/mock-erp .
EXPOSE 8081
CMD ["./mock-erp"]
