FROM golang:1.26.2-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

COPY vendor ./vendor

# RUN go mod download

COPY . .

# RUN go build -o erpbridge-server services/erpbridge-server/main.go

RUN go build -mod=vendor -o erpbridge-server services/erpbridge-server/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/erpbridge-server .

EXPOSE 8080

CMD ["./erpbridge-server"]
