package routes

import (
	"github.com/gofiber/contrib/websocket"
	"github.com/gofiber/fiber/v2"
	"github.com/sanjeewa/agentic-orchestrator/internal/api/handlers"
	"github.com/sanjeewa/agentic-orchestrator/internal/api/middlewares"
)

func Register(app *fiber.App, h *handlers.Handler) {
	app.Get("/healthz", h.Health)
	app.Get("/ws/*", websocket.New(h.WebSocketEvents))

	api := app.Group(h.Cfg.APIBasePath)
	api.Get("/health", h.Health)

	auth := api.Group("/auth")
	auth.Post("/login", h.Login)
	auth.Post("/register", h.Register)
	auth.Post("/refresh", h.Refresh)
	auth.Post("/forgot-password", h.ForgotPassword)
	auth.Post("/reset-password", h.ResetPassword)
	auth.Post("/verify-email", h.VerifyEmail)
	auth.Get("/oauth/:provider/authorize", h.OAuthAuthorize)
	auth.Get("/oauth/:provider/callback", h.OAuthCallback)

	protected := api.Group("", middlewares.Auth(h.Cfg.JWTSecret, h.Cfg.AllowDevAuth))

	protected.Post("/auth/logout", h.Logout)
	protected.Get("/auth/me", h.Me)
	protected.Post("/auth/2fa/verify", h.TwoFactorVerify)
	protected.Post("/auth/2fa/enable", h.TwoFactorEnable)
	protected.Post("/auth/2fa/disable", h.TwoFactorDisable)

	protected.Get("/dashboard/summary", h.DashboardSummary)
	protected.Get("/dashboard/activity", h.DashboardActivity)
	protected.Get("/dashboard/health", h.DashboardHealth)
	protected.Get("/dashboard/recent-workflows", h.RecentWorkflows)

	protected.Get("/workflows/templates", h.ListTemplates)
	protected.Post("/workflows/templates", h.CreateTemplate)
	protected.Post("/workflows/templates/:id/use", h.UseTemplate)
	protected.Get("/workflows", h.ListWorkflows)
	protected.Post("/workflows", h.CreateWorkflow)
	protected.Get("/workflows/:id", h.GetWorkflow)
	protected.Patch("/workflows/:id", h.UpdateWorkflow)
	protected.Delete("/workflows/:id", h.DeleteWorkflow)
	protected.Post("/workflows/:id/duplicate", h.DuplicateWorkflow)
	protected.Post("/workflows/:id/publish", h.PublishWorkflow)
	protected.Post("/workflows/:id/archive", h.ArchiveWorkflow)
	protected.Post("/workflows/:id/validate", h.ValidateWorkflow)
	protected.Post("/workflows/:id/run", h.RunWorkflow)
	protected.Get("/workflows/:id/yaml", h.GetWorkflowYAML)
	protected.Put("/workflows/:id/yaml", h.PutWorkflowYAML)
	protected.Get("/workflows/:id/canvas", h.GetWorkflowCanvas)
	protected.Put("/workflows/:id/canvas", h.PutWorkflowCanvas)
	protected.Get("/workflows/:id/versions", h.WorkflowVersions)
	protected.Post("/workflows/:id/restore/:versionId", h.RestoreWorkflowVersion)
	protected.Get("/workflows/:id/executions", h.WorkflowExecutions)

	protected.Post("/synthesis", h.Synthesize)
	protected.Post("/synthesis/validate", h.SynthesisValidate)
	protected.Post("/synthesis/preview-flow", h.SynthesisPreviewFlow)
	protected.Post("/synthesis/explain", h.SynthesisExplain)
	protected.Get("/tools/catalog", h.ToolsCatalog)
	protected.Get("/rules/catalog", h.RulesCatalog)
	protected.Post("/semantic-search", h.SemanticSearch)
	protected.Post("/canvas/validate-workflow", h.CanvasValidateWorkflow)

	protected.Get("/chat/sessions", h.ListChatSessions)
	protected.Post("/chat/sessions", h.CreateChatSession)
	protected.Get("/chat/sessions/:id", h.GetChatSession)
	protected.Patch("/chat/sessions/:id", h.UpdateChatSession)
	protected.Delete("/chat/sessions/:id", h.DeleteChatSession)
	protected.Post("/chat/sessions/:id/messages", h.SendChatMessage)

	protected.Get("/executions", h.ListExecutions)
	protected.Get("/executions/:id", h.GetExecution)
	protected.Get("/executions/:id/logs", h.ExecutionLogs)
	protected.Get("/executions/:id/timeline", h.ExecutionTimeline)
	protected.Get("/executions/:id/healing-report", h.ExecutionHealingReport)
	protected.Post("/executions/:id/cancel", h.CancelExecution)
	protected.Post("/executions/:id/retry", h.RetryExecution)

	protected.Get("/analytics/summary", h.AnalyticsSummary)
	protected.Get("/analytics/performance", h.AnalyticsPerformance)
	protected.Get("/analytics/usage", h.AnalyticsUsage)
	protected.Get("/analytics/self-healing", h.AnalyticsSelfHealing)
	protected.Get("/analytics/latency", h.AnalyticsLatency)
	protected.Get("/analytics/f1-score", h.AnalyticsF1Score)
	protected.Get("/analytics/activity-heatmap", h.AnalyticsActivityHeatmap)
	protected.Get("/analytics/cost-trends", h.AnalyticsCostTrends)

	protected.Get("/users", h.ListUsers)
	protected.Post("/users", h.CreateUser)
	protected.Post("/users/invite", h.InviteUser)
	protected.Get("/users/:id", h.GetUser)
	protected.Patch("/users/:id", h.UpdateUser)
	protected.Delete("/users/:id", h.DeleteUser)
	protected.Post("/users/:id/activate", h.ActivateUser)
	protected.Post("/users/:id/suspend", h.SuspendUser)
	protected.Get("/roles", h.ListRoles)
	protected.Post("/roles", h.CreateRole)
	protected.Get("/roles/:id", h.GetRole)
	protected.Patch("/roles/:id", h.UpdateRole)
	protected.Delete("/roles/:id", h.DeleteRole)
	protected.Get("/permissions", h.ListPermissions)
	protected.Get("/permissions/matrix", h.PermissionMatrix)
	protected.Get("/audit/export", h.ExportAudit)
	protected.Get("/audit", h.ListAudit)
	protected.Get("/audit/:id", h.GetAudit)

	protected.Get("/profile", h.GetProfile)
	protected.Patch("/profile", h.UpdateProfile)
	protected.Patch("/profile/security", h.UpdateSecurity)
	protected.Get("/profile/notifications", h.GetNotificationPreferences)
	protected.Patch("/profile/notifications", h.UpdateNotificationPreferences)
	protected.Get("/profile/api-keys", h.ListAPIKeys)
	protected.Post("/profile/api-keys", h.CreateAPIKey)
	protected.Delete("/profile/api-keys/:id", h.DeleteAPIKey)

	protected.Get("/settings", h.GetSettings)
	protected.Patch("/settings", h.PatchSettings)
	protected.Get("/settings/general", h.GetGeneralSettings)
	protected.Patch("/settings/general", h.PatchGeneralSettings)
	protected.Get("/settings/llm", h.GetLLMSettings)
	protected.Patch("/settings/llm", h.PatchLLMSettings)
	protected.Get("/settings/rbac", h.GetRBACSettings)
	protected.Patch("/settings/rbac", h.PatchRBACSettings)
	protected.Get("/settings/webhooks", h.ListWebhooks)
	protected.Post("/settings/webhooks", h.CreateWebhook)
	protected.Patch("/settings/webhooks/:id", h.UpdateWebhook)
	protected.Delete("/settings/webhooks/:id", h.DeleteWebhook)
	protected.Post("/settings/webhooks/:id/test", h.TestWebhook)

	protected.Get("/integrations", h.ListIntegrations)
	protected.Post("/integrations", h.CreateIntegration)
	protected.Get("/integrations/:id", h.GetIntegration)
	protected.Patch("/integrations/:id", h.UpdateIntegration)
	protected.Delete("/integrations/:id", h.DeleteIntegration)
	protected.Post("/integrations/:id/test", h.TestIntegration)
	protected.Post("/integrations/:id/connect", h.ConnectIntegration)
	protected.Post("/integrations/:id/disconnect", h.DisconnectIntegration)

	protected.Get("/notifications", h.ListNotifications)
	protected.Patch("/notifications/read-all", h.MarkAllNotificationsRead)
	protected.Patch("/notifications/:id/read", h.MarkNotificationRead)
	protected.Delete("/notifications/:id", h.DeleteNotification)
	protected.Post("/upload", h.Upload)
	protected.Get("/upload/:id", h.GetUpload)
	protected.Delete("/upload/:id", h.DeleteUpload)
	protected.Post("/upload/workflow-import", h.ImportWorkflow)
}
